# Version format.
version: "3.0.0.{build}"

# Only build the master branch.
branches:
  only:
    - master

# Do not increment build number after pull requests.
pull_requests:
  do_not_increment_build_number: true

# Do not start a new build when a new Git tag is created.
skip_tags: true
  
# Set the clone directory on the buildbot.
clone_folder: C:\projects\processhacker2
  
# Immediately finish build if something fails.
matrix:
  fast_finish: true

# Install inno setup.
install:
  - choco install -y InnoSetup
  
# Disable running any test assemblies.
test: off

# Run custom build script.
build_script:
- ps: .\build\internal\build.ps1

# Deploy these files for download.
artifacts:
- path: .\processhacker-build-setup.exe
  name: processhacker-build-setup.exe
- path: .\processhacker-build-bin.zip
  name: processhacker-build-bin.zip
- path: .\processhacker-build-sdk.zip
  name: processhacker-build-sdk.zip
- path: .\processhacker-build-src.zip
  name: processhacker-build-src.zip
- path: .\processhacker-build-pdb.zip
  name: processhacker-build-pdb.zip
- path: .\processhacker-build-checksums.txt
  name: processhacker-build-checksums.txt

# Setup build notifications.
notifications:
- provider: Email
  to:
  - dmex04@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false